version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/src/tools/fuse"
    schedule:
      interval: "daily"
    labels:
      - "lang/python"

  - package-ecosystem: "npm"
    directory: "/src/tools/webd"
    schedule:
      interval: "daily"
    labels:
      - "lang/web"

  - package-ecosystem: "npm"
    directory: "/src/tools/webui"
    schedule:
      interval: "daily"
    labels:
      - "lang/web"

  - package-ecosystem: "cargo"
    directory: "/src/bindings/rust"
    schedule:
      interval: "daily"
    labels:
      - "lang/rust"

  - package-ecosystem: "npm"
    directory: "/src/tools/website"
    schedule:
      interval: "daily"
    labels:
      - "lang/web"

  - package-ecosystem: "gomod"
    directory: "/src/tools/elektrad"
    schedule:
      interval: "daily"
    labels:
      - "lang/go"
